name: ksb
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.0+21

environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  # state management
  flutter_bloc: ^8.1.3
  # router
  go_router: ^11.1.2
  # data
  shared_preferences: ^2.2.1
  # Network
  dio:
  pretty_dio_logger: ^1.3.1
  # ui
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.4
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  otp_text_field: ^1.1.3
  pluto_grid: ^7.0.2
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.6.0
  easy_stepper: ^0.8.1
  progress_stepper: ^1.0.0
  readmore: ^2.2.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.4
  awesome_snackbar_content: ^0.1.3
  smooth_page_indicator: ^1.1.0
  top_snackbar_flutter: ^3.1.0
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.2.0
  # flutter_facebook_auth: ^6.0.2
  image_picker: ^1.0.4
  intl: ^0.18.1
  url_launcher: ^6.2.1
  buttons_tabbar: ^1.3.8
  dropdown_button2: ^2.3.9
  awesome_notifications: ^0.8.2
  pusher_client: ^2.0.0
  dot_navigation_bar: ^1.0.2
  flutter_staggered_animations: ^1.1.1
  easy_localization: ^3.0.3
  lottie: ^2.7.0
  water_drop_nav_bar: ^2.2.0+5
  chewie: ^1.7.1
  video_player:
  open_file: ^3.3.2
  path_provider: ^2.1.1
  appinio_video_player: ^1.2.2
  animate_do: ^3.1.2
  firebase_core: ^2.22.0
  google_sign_in: ^6.1.6
  flutter_facebook_auth: ^6.0.3
  firebase_auth: ^4.14.1
  mobile_scanner: ^3.5.5
  flutter_barcode_scanner: ^2.0.0
  connectivity_plus: ^5.0.2
  intl_phone_number_input: ^0.7.4
  intl_phone_field: ^3.2.0
  device_preview: ^1.1.0
  flutter_slidable: ^3.0.1
  location: ^5.0.3
  geocoding: ^2.1.1
  youtube_player_flutter: ^8.1.2
  audioplayers: ^5.2.1
  permission_handler: ^11.2.0
  flutter_sound: ^9.2.13
  internet_connection_checker: ^1.0.0+1
  flutter_swipe_action_cell: ^3.1.3
  timeago: ^3.6.1
  emoji_picker_flutter: ^1.6.2
  chat_bubbles: ^1.5.0
  file_picker: ^6.1.1
  firebase_messaging: ^14.7.15
  flutter_map: ^5.0.0
  flutter_form_builder: ^9.2.1



dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/json/
    - assets/translations/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/worksans/WorkSans-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/worksans/WorkSans-VariableFont_wght.ttf


